#牛
execute @e[tag=L_F_AS_A] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:cow",CustomName:"耕耘牛",DeathLootTable:"Labyrinth_Forest:mobs/farming_cow",Tags:["farming_cow","L_F"],Passengers:[{id:"minecraft:area_effect_cloud",Particle:blockcrack,ParticleParam1:3,Radius:1f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#兔
execute @e[tag=L_F_AS_B] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:rabbit",CustomName:"雪兔哥",DeathLootTable:"Labyrinth_Forest:mobs/snow_rabbit",Tags:["snow_rabbit","L_F"],RabbitType:1,Attributes:[{Name:generic.movementSpeed,Base:0.1}],Passengers:[{id:"minecraft:area_effect_cloud",Particle:snowshovel ,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#羊駝
execute @e[tag=L_F_AS_C] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:llama",DeathLootTable:"Labyrinth_Forest:mobs/Kuzco_llama",Tags:["Kuzco_llama","L_F"],Tame:1,DecorItem:{id:"minecraft:carpet",Count:1b,Damage:14s,tag:{display:{Name:"國王的新衣",Lore:["聰明的人才看不到","","","咦？"]},HideFlags:3,ench:[{id:21,lvl:1}]}},Passengers:[{id:"minecraft:area_effect_cloud",Particle:note ,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#鐵巨人
execute @e[tag=L_F_AS_D] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:villager_golem",CatType:3,CustomName:"史塔克",DeathLootTable:"Labyrinth_Forest:mobs/Stark_villager_golem",Tags:["Stark_villager_golem","L_F"],Attributes:[{Name:generic.maxHealth,Base:30}],Health:30.0f,Passengers:[{id:"minecraft:area_effect_cloud",Particle: happyVillager,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:2,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#安德
execute @e[tag=L_F_AS_E] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:enderman",CustomName:"會害羞",Tags:["so_shy_enderman","L_F"],DeathLootTable:"Labyrinth_Forest:mobs/so_shy_enderman",Attributes:[{Name:generic.maxHealth,Base:20}],Health:20.0f,Passengers:[{id:"minecraft:area_effect_cloud",Particle:mobSpell,Color:16743913,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:300,DurationOnUse:-300f,WaitTime:280,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}]}]},SpawnCount:2,SpawnRange:1,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#毒蜘蛛
execute @e[tag=L_F_AS_F] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:cave_spider",CustomName:"不想說",Tags:["do_not_want_tell_cave_spider","L_F"],DeathLootTable:"Labyrinth_Forest:mobs/do_not_want_tell_cave_spider",Passengers:[{id:"minecraft:area_effect_cloud",Particle:angryVillager,ParticleParam1:88,Radius:0.5f,RadiusOnUse:-0.01f,Duration:300,DurationOnUse:-300f,WaitTime:280,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}]}]},SpawnCount:2,SpawnRange:1,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#豬
execute @e[tag=L_F_AS_G] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:pig",CustomName:"打滾豬",DeathLootTable:"Labyrinth_Forest:mobs/rolling_pig",Tags:["rolling_pig","L_F"],Passengers:[{id:"minecraft:area_effect_cloud",Particle:blockcrack,ParticleParam1:88,Radius:1f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#骷髏
execute @e[tag=L_F_AS_H] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"skeleton",CustomName:"大笨驢",Tags:["wood_head_skeleton","L_F"],ArmorItems:[{},{},{},{id:"minecraft:log",Count:1b}],ArmorDropChances:[0.085F,0.085F,0.085F,0.0F],Attributes:[{Name:generic.knockbackResistance,Base:1}],Health:15.0f,DeathLootTable:"Labyrinth_Forest:mobs/wood_head_skeleton",Passengers:[{id:"minecraft:area_effect_cloud",Particle:fallingdust,ParticleParam1:88,Radius:0.5f,RadiusOnUse:-0.01f,Duration:300,DurationOnUse:-300f,WaitTime:280,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}]}]},SpawnCount:2,SpawnRange:1,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#羊
execute @e[tag=L_F_AS_I] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:sheep",CustomName:"jeb_",DeathLootTable:"Labyrinth_Forest:mobs/rainbow_sheep",Tags:["rainbowSheep","L_F"],Passengers:[{id:"minecraft:area_effect_cloud",Particle:witchMagic,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#地獄豬
execute @e[tag=L_F_AS_J] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:zombie_pigman",CustomName:"愛開趴",Tags:["party_zombie_pigma","L_F"],DeathLootTable:"Labyrinth_Forest:mobs/party_zombie_pigman",Attributes:[{Name:generic.armor,Base:15}],Passengers:[{id:"minecraft:area_effect_cloud",Particle:heart,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:300,DurationOnUse:-300f,WaitTime:280,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}]}]},SpawnCount:2,SpawnRange:1,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#貓
execute @e[tag=L_F_AS_K] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:ocelot",CatType:3,CustomName:"主上大人",DeathLootTable:"Labyrinth_Forest:mobs/master_cat",Tags:["master_cat","L_F"],Attributes:[{Name:generic.movementSpeed,Base:0.2}],Passengers:[{id:"minecraft:area_effect_cloud",Particle: fallingdust ,ParticleParam1:12,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#殭屍
execute @e[tag=L_F_AS_L] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"zombie",CustomName:"石頭腦",Tags:["stone_head_zombie","L_F"],ArmorItems:[{},{},{},{id:"minecraft:stone",Count:1b}],ArmorDropChances:[0.085F,0.085F,0.085F,0.0F],Attributes:[{Name:generic.knockbackResistance,Base:1},{Name:zombie.spawnReinforcements,Base:0.0F}],Health:15.0f,DeathLootTable:"Labyrinth_Forest:mobs/stone_head_zombie",Passengers:[{id:"minecraft:area_effect_cloud",Particle:fallingdust,ParticleParam1:1,Radius:0.5f,RadiusOnUse:-0.01f,Duration:300,DurationOnUse:-300f,WaitTime:280,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}]}]},SpawnCount:2,SpawnRange:1,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#史萊姆
execute @e[tag=L_F_AS_M] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],DeathLootTable:"N/A",Health:0.0f,NoAI:1,Silent:1,Passengers:[{id:"slime",CustomName:"Lv.1",Tags:["level_one_slime","L_F"],Attributes:[{Name:generic.armor,Base:30}],Size:0,DeathLootTable:"Labyrinth_Forest:mobs/level_one_slime",Passengers:[{id:"minecraft:area_effect_cloud",Particle:slime,Radius:0.2f,RadiusOnUse:-0.01f,Duration:300,DurationOnUse:-300f,WaitTime:280,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#狗
execute @e[tag=L_F_AS_N] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:wolf",CatType:3,CustomName:"自宅警備犬",DeathLootTable:"Labyrinth_Forest:mobs/indoor_dog",Tags:["indoor_dog","L_F"],Attributes:[{Name:generic.maxHealth,Base:10},{Name:generic.armor,Base:20}],Health:10.0f,Passengers:[{id:"minecraft:area_effect_cloud",Particle: enchantmenttable,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#雞
execute @e[tag=L_F_AS_O] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:chicken",CustomName:"海底雞",DeathLootTable:"Labyrinth_Forest:mobs/underwater_chicken",Tags:["underwater_chicken","L_F"],Passengers:[{id:"minecraft:area_effect_cloud",Particle:droplet,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
#苦力怕
execute @e[tag=L_F_AS_P] ~ ~ ~ /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:creeper",CustomName:"心裡苦",Tags:["feel_bad_creeper","L_F"],Attributes:[{Name:generic.movementSpeed,Base:0.4},{Name:generic.followRange,Base:35}],ExplosionRadius:2,Fuse:15,Health:10.0f,DeathLootTable:"Labyrinth_Forest:mobs/feel_bad_creeper",Passengers:[{id:"minecraft:area_effect_cloud",Particle:largesmoke,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:300,DurationOnUse:-300f,WaitTime:280,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}]}]},SpawnCount:2,SpawnRange:1,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
