# 測試用腳本
# Usage
# function Labyrinth_Forest:test

/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:sheep",CustomName:"jeb_",DeathLootTable:"Labyrinth_Forest:mobs/rainbow_sheep",Tags:["rainbowSheep","L_F"],PersistenceRequired:0,Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle:witchMagic,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:cow",CustomName:"耕耘牛",DeathLootTable:"Labyrinth_Forest:mobs/farming_cow",Tags:["farming_cow","L_F"],PersistenceRequired:0,Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle:blockcrack,ParticleParam1:3,Radius:1f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:pig",CustomName:"打滾豬",DeathLootTable:"Labyrinth_Forest:mobs/rolling_pig",Tags:["rolling_pig","L_F"],PersistenceRequired:0,Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle:blockcrack,ParticleParam1:88,Radius:1f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:chicken",CustomName:"海底雞",DeathLootTable:"Labyrinth_Forest:mobs/underwater_chicken",Tags:["underwater_chicken","L_F"],PersistenceRequired:0,Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle:droplet,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:wolf",CustomName:"自宅警備犬",DeathLootTable:"Labyrinth_Forest:mobs/indoor_dog",Tags:["indoor_dog","L_F"],PersistenceRequired:0,Attributes:[{Name:generic.maxHealth,Base:10},{Name:generic.armor,Base:20}],Health:10.0f,Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle: enchantmenttable,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:ocelot",CatType:3,CustomName:"主上大人",DeathLootTable:"Labyrinth_Forest:mobs/master_cat",Tags:["master_cat","L_F"],PersistenceRequired:0,Attributes:[{Name:generic.movementSpeed,Base:0.2}],Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle: fallingdust ,ParticleParam1:12,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:rabbit",RabbitType:1,CustomName:"雪兔哥",DeathLootTable:"Labyrinth_Forest:mobs/snow_rabbit",Tags:["snow_rabbit","L_F"],PersistenceRequired:0,Attributes:[{Name:generic.movementSpeed,Base:0.1}],Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle:snowshovel ,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}

/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {SpawnData:{id:"minecraft:spider",Tags:["L_F"],Health:0.0f,NoAI:1,Silent:1,DeathLootTable:"N/A",ActiveEffects:[{Id:14,Amplifier:0,Duration:100,ShowParticles:0b}],Passengers:[{id:"minecraft:llama",CustomName:"庫斯德",DeathLootTable:"Labyrinth_Forest:mobs/Kuzco_llama",Tags:["Kuzco_llama","L_F"],PersistenceRequired:0,Tame:1,DecorItem:{id:"minecraft:carpet",Count:1b,Damage:14s,tag:{display:{Name:"國王的新衣",Lore:["聰明的人才看不到","","","","咦？"]},HideFlags:3,ench:[{id:21,lvl:1}]}},Passengers:[{id:"minecraft:area_effect_cloud",CustomName:"迷藏森林",Particle:note ,ParticleParam1:0,Radius:0.5f,RadiusOnUse:-0.01f,Duration:600,DurationOnUse:-600f,WaitTime:580,Effects:[{Id:6,Amplifier:50,Duration:20},{Id:7,Amplifier:50,Duration:20}],Tags:["killEffect","L_F"]}]}]},SpawnCount:4,SpawnRange:2,RequiredPlayerRange:32,Delay:100,MinSpawnDelay:60,MaxSpawnDelay:300,MaxNearbyEntities:12}
